[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://uolhwhuhuiqjyhlwqsjm.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbGh3aHVodWlxanlobHdxc2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTI1MjMsImV4cCI6MjA2OTg4ODUyM30.1EnagPSnyDA_DxM5UKlhaX7FWhHT1fzPoGzQk4maaZQ"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200